development:
  adapter: postgresql
  encoding: unicode
  database: crossbone_development
  host: localhost
  pool: 5
  username: dylanoshea
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: crossbone_test
  host: localhost
  pool: 5
  username: dylanoshea
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: crossbone_production
  host: localhost
  pool: 5
  username: dylanoshea
  password:
